services:
  entrypoint:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports: 
      - "${LISTENER_PORT}:8080"
    restart: "unless-stopped"
    healthcheck:
      test: curl localhost:8080/health -f
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      - MYSQL_HOSTNAME=mysql:3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=gobrax
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:latest
    restart: "unless-stopped"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 50